[workspace]
# Whether to inherit the version from the workspace
inherit_version = true

# Whether to link all dependencies to their workspace versions
link_workspace_deps = true

# Whether to update the versions of workspace dependencies when versioning
update_workspace_deps = true

# Custom publish order
publish_order = [
  "floxide-core",
  "floxide-macros",
  "floxide-redis",
  "floxide"
]
