site_name: Floxide Documentation
site_description: Documentation for the Floxide framework - A type-safe, composable directed graph workflow system written in Rust
site_author: Floxide Team
repo_url: https://github.com/aitoroses/floxide
repo_name: aitoroses/floxide
edit_uri: edit/main/docs/

theme:
  name: terminal
  palette: dark
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
  font:
    text: Roboto
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: false
      language_prefix: language-
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Error Handling: getting-started/error-handling.md
  - Core Concepts:
    - Overview: core-concepts/overview.md
    - Nodes: core-concepts/nodes.md
    - Workflows: core-concepts/workflows.md
    - Cyclic Workflows: core-concepts/cyclic-workflows.md
    - Actions: core-concepts/actions.md
    - Contexts: core-concepts/contexts.md
  - Guides:
    - Event-Driven Architecture: guides/event_driven_architecture.md
    - Using Mermaid Diagrams: guides/using-mermaid-diagrams.md
  - Examples:
    - Basic Workflow: examples/basic-workflow.md
    - Event-Driven Workflow: examples/event-driven-workflow.md
    - Timer Node: examples/timer-node.md
    - Reactive Node: examples/reactive-node.md
    - Transform Node: examples/transform-node.md
    - Long-Running Node: examples/longrunning-node.md
    - Batch Processing: examples/batch-processing.md
  - Architecture:
    - ADR Process: architecture/adr-process.md
    - Core Framework Abstractions: architecture/core-framework-abstractions.md
    - Project Structure: architecture/project-structure.md
    - Async Runtime Selection: architecture/async-runtime-selection.md
    - Node Lifecycle Methods: architecture/node-lifecycle-methods.md
    - Event-Driven Workflow Pattern: architecture/event-driven-workflow-pattern.md
    - Reactive Node Implementation: architecture/reactive-node-implementation.md
    - Timer Node Implementation: architecture/timer-node-implementation.md
    - Long-Running Node Implementation: architecture/longrunning-node-implementation.md
    - Transform Node Implementation: architecture/transform-node-implementation.md
    - Batch Processing Implementation: architecture/batch-processing-implementation.md
  - API Reference:
    - floxide-core: api/floxide-core.md
    - floxide-transform: api/floxide-transform.md
    - floxide-event: api/floxide-event.md
    - floxide-timer: api/floxide-timer.md
    - floxide-reactive: api/floxide-reactive.md
    - floxide-longrunning: api/floxide-longrunning.md
    - floxide-batch: api/floxide-batch.md
  - Contributing: contributing.md