site_name: Floxide Documentation
site_description: Documentation for the Floxide framework - A type-safe, composable directed graph workflow system written in Rust
site_author: Floxide Team
repo_url: https://github.com/aitoroses/floxide
repo_name: aitoroses/floxide
edit_uri: edit/main/docs/

theme:
  name: terminal
  palette: dark
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
  font:
    text: Roboto
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: false
      language_prefix: language-
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

plugins:
  - search

nav:

  - Floxide Tutorial:
      - Introduction: floxide-tutorial/index.md
      - "Chapter 1: Transition Enum": floxide-tutorial/01__transition__enum_.md
      - "Chapter 2: Node Trait & node! Macro": floxide-tutorial/02__node__trait____node___macro_.md
      - "Chapter 3: WorkflowCtx & Context Trait": floxide-tutorial/03__workflowctx_____context__trait_.md
      - "Chapter 4: Workflow Trait & workflow! Macro": floxide-tutorial/04__workflow__trait____workflow___macro_.md
      - "Chapter 5: WorkQueue Trait": floxide-tutorial/05__workqueue__trait_.md
      - "Chapter 6: Checkpoint & CheckpointStore Trait": floxide-tutorial/06__checkpoint_____checkpointstore__trait_.md
      - "Chapter 7: DistributedWorker": floxide-tutorial/07__distributedworker__.md
      - "Chapter 8: DistributedOrchestrator": floxide-tutorial/08__distributedorchestrator__.md
      - "Chapter 9: Distributed Stores": floxide-tutorial/09_distributed_stores___runinfostore____metricsstore____errorstore____livenessstore____workitemstatestore___.md
      - "Chapter 10: RetryPolicy & RetryNode": floxide-tutorial/10__retrypolicy_____retrynode__.md